services:
  - name: api-rest-icl
    type: web
    buildCommand: npm install && npm run build
    startCommand: npm start
    env:
      DATABASE_URL: postgres://postgres:Lm03051971@localhost:4000/icl_web