insert into campostablas (id_menu, tabla, nombre_campo, titulo_campo, tipo, backend, ancho, valores) values (2,'area','descripcion_area','Descripción de área','character','',255,'');
insert into campostablas (id_menu, tabla, nombre_campo, titulo_campo, tipo, backend, ancho, valores) values (2,'area','abreviacion_area','Abreviación de área','char','',2,'');
insert into campostablas (id_menu, tabla, nombre_campo, titulo_campo, tipo, backend, ancho, valores) values (3,'categoría','descripcion_categoria','Descripción de categoría','character','',255,'');
insert into campostablas (id_menu, tabla, nombre_campo, titulo_campo, tipo, backend, ancho, valores) values (11,'convenio','descripcion_convenio','Descripción de convenio','character','',255,'');
insert into campostablas (id_menu, tabla, nombre_campo, titulo_campo, tipo, backend, ancho, valores) values (11,'convenio','fecha_convenio','Fecha de Convenio','date','',10,'');
insert into campostablas (id_menu, tabla, nombre_campo, titulo_campo, tipo, backend, ancho, valores) values (11,'convenio','url_documento_convenio','Link del convenio','character','',255,'');
insert into campostablas (id_menu, tabla, nombre_campo, titulo_campo, tipo, backend, ancho, valores) values (11,'convenio','contenido_documento_convenio','Documento del convenio','bytea','',1000,'');
insert into campostablas (id_menu, tabla, nombre_campo, titulo_campo, tipo, backend, ancho, valores) values (11,'convenio','id_distrito','Distrito','endpoint','/distritos',4,'id');
insert into campostablas (id_menu, tabla, nombre_campo, titulo_campo, tipo, backend, ancho, valores) values (11,'convenio','id_provincia','Provincia','endpoint','/provincias',4,'id');
insert into campostablas (id_menu, tabla, nombre_campo, titulo_campo, tipo, backend, ancho, valores) values (11,'convenio','id_departamento','Departamento','endpoint','/departamentos',4,'id');
insert into campostablas (id_menu, tabla, nombre_campo, titulo_campo, tipo, backend, ancho, valores) values (12,'convocatoria','descripcion_convocatoria','Descripción de Convocatoria','character','',255,'');
insert into campostablas (id_menu, tabla, nombre_campo, titulo_campo, tipo, backend, ancho, valores) values (12,'convocatoria','tipo_convocatoria','Tipo de convocatoria','array','',3,'[CAS,PPP]');
insert into campostablas (id_menu, tabla, nombre_campo, titulo_campo, tipo, backend, ancho, valores) values (12,'convocatoria','numero_convocatoria','Número de convocatoria','number','',10,'');
insert into campostablas (id_menu, tabla, nombre_campo, titulo_campo, tipo, backend, ancho, valores) values (12,'convocatoria','periodo_convocatoria','Periodo de convocatoria','number','',10,'');
insert into campostablas (id_menu, tabla, nombre_campo, titulo_campo, tipo, backend, ancho, valores) values (12,'convocatoria','flag_adjunto','Tipo de adjunto','array','',3,'[URL,BIN]');
insert into campostablas (id_menu, tabla, nombre_campo, titulo_campo, tipo, backend, ancho, valores) values (12,'convocatoria','url_anexos','Link de los anexos','character','',255,'');
insert into campostablas (id_menu, tabla, nombre_campo, titulo_campo, tipo, backend, ancho, valores) values (12,'convocatoria','url_comunicacion1','Link de la comunicación 1','character','',255,'');
insert into campostablas (id_menu, tabla, nombre_campo, titulo_campo, tipo, backend, ancho, valores) values (12,'convocatoria','url_comunicacion2','Link de la comunicación 2','character','',255,'');
insert into campostablas (id_menu, tabla, nombre_campo, titulo_campo, tipo, backend, ancho, valores) values (12,'convocatoria','url_comunicacion3','Link de la comunicación 3','character','',255,'');
insert into campostablas (id_menu, tabla, nombre_campo, titulo_campo, tipo, backend, ancho, valores) values (12,'convocatoria','url_comunicaciones','Link de la comunicaciones','character','',255,'');
insert into campostablas (id_menu, tabla, nombre_campo, titulo_campo, tipo, backend, ancho, valores) values (12,'convocatoria','url_aviso','Link de aviso','character','',255,'');
insert into campostablas (id_menu, tabla, nombre_campo, titulo_campo, tipo, backend, ancho, valores) values (12,'convocatoria','url_resultado_evaluacion_curricular','Link resultado evaluación curricular','character','',255,'');
insert into campostablas (id_menu, tabla, nombre_campo, titulo_campo, tipo, backend, ancho, valores) values (12,'convocatoria','url_resultado_examen','Link resultado examen','character','',255,'');
insert into campostablas (id_menu, tabla, nombre_campo, titulo_campo, tipo, backend, ancho, valores) values (12,'convocatoria','url_resultado_entrevista','Link resultado entrevista','character','',255,'');
insert into campostablas (id_menu, tabla, nombre_campo, titulo_campo, tipo, backend, ancho, valores) values (12,'convocatoria','url_puntaje_final','Link puntaje final','character','',255,'');
insert into campostablas (id_menu, tabla, nombre_campo, titulo_campo, tipo, backend, ancho, valores) values (12,'convocatoria','contenido_anexos','Documento de anexos','character','',1000,'');
insert into campostablas (id_menu, tabla, nombre_campo, titulo_campo, tipo, backend, ancho, valores) values (12,'convocatoria','contenido_comunicacion1','Documento comunicación 1','character','',1000,'');
insert into campostablas (id_menu, tabla, nombre_campo, titulo_campo, tipo, backend, ancho, valores) values (12,'convocatoria','contenido_comunicacion2','Documento comunicación 2','character','',1000,'');
insert into campostablas (id_menu, tabla, nombre_campo, titulo_campo, tipo, backend, ancho, valores) values (12,'convocatoria','contenido_comunicacion3','Documento comunicación 3','character','',1000,'');
insert into campostablas (id_menu, tabla, nombre_campo, titulo_campo, tipo, backend, ancho, valores) values (12,'convocatoria','contenido_comunicaciones','Documento comunicaciones','character','',1000,'');
insert into campostablas (id_menu, tabla, nombre_campo, titulo_campo, tipo, backend, ancho, valores) values (12,'convocatoria','contenido_aviso','Documento Aviso','character','',1000,'');
insert into campostablas (id_menu, tabla, nombre_campo, titulo_campo, tipo, backend, ancho, valores) values (12,'convocatoria','contenido_resultado_evaluacion_curricular','Documento resultado evaluación curricular','character','',1000,'');
insert into campostablas (id_menu, tabla, nombre_campo, titulo_campo, tipo, backend, ancho, valores) values (12,'convocatoria','contenido_resultado_examen','Documento resultado examen','character','',1000,'');
insert into campostablas (id_menu, tabla, nombre_campo, titulo_campo, tipo, backend, ancho, valores) values (12,'convocatoria','contenido_resultado_entrevista','Documento resultado entrevista','character','',1000,'');
insert into campostablas (id_menu, tabla, nombre_campo, titulo_campo, tipo, backend, ancho, valores) values (12,'convocatoria','contenido_puntaje_final','Contenido puntaje final','character','',1000,'');
insert into campostablas (id_menu, tabla, nombre_campo, titulo_campo, tipo, backend, ancho, valores) values (12,'convocatoria','id_area','Area','endpoint','/areas',2,'id');
insert into campostablas (id_menu, tabla, nombre_campo, titulo_campo, tipo, backend, ancho, valores) values (12,'convocatoria','estado_convocatoria','Estado convocatoria','array','',15,'[Cancelado,Cerrado,Desierto]');
insert into campostablas (id_menu, tabla, nombre_campo, titulo_campo, tipo, backend, ancho, valores) values (13,'curso','image','Imagen del curso','character','',255,'');
insert into campostablas (id_menu, tabla, nombre_campo, titulo_campo, tipo, backend, ancho, valores) values (13,'curso','video','Video del curso','character','',255,'');
insert into campostablas (id_menu, tabla, nombre_campo, titulo_campo, tipo, backend, ancho, valores) values (13,'curso','title','Tìtulo','character','',255,'');
insert into campostablas (id_menu, tabla, nombre_campo, titulo_campo, tipo, backend, ancho, valores) values (13,'curso','content','Descripción del Curso','character','',255,'');
insert into campostablas (id_menu, tabla, nombre_campo, titulo_campo, tipo, backend, ancho, valores) values (13,'curso','link','Link para más información','character','',255,'');
insert into campostablas (id_menu, tabla, nombre_campo, titulo_campo, tipo, backend, ancho, valores) values (14,'directiva','periodo_resolucion','Año resolución','number','',10,'');
insert into campostablas (id_menu, tabla, nombre_campo, titulo_campo, tipo, backend, ancho, valores) values (14,'directiva','numero_resolucion','Número resolución','number','',10,'');
insert into campostablas (id_menu, tabla, nombre_campo, titulo_campo, tipo, backend, ancho, valores) values (14,'directiva','adicional_resolucion','Número adicional','char','',1,'');
insert into campostablas (id_menu, tabla, nombre_campo, titulo_campo, tipo, backend, ancho, valores) values (14,'directiva','sumilla_resolucion','Sumilla de resolución','character','',1500,'');
insert into campostablas (id_menu, tabla, nombre_campo, titulo_campo, tipo, backend, ancho, valores) values (14,'directiva','url_documento_resolucion','Link resolución','character','',255,'');
insert into campostablas (id_menu, tabla, nombre_campo, titulo_campo, tipo, backend, ancho, valores) values (14,'directiva','abreviacion_area','Abreviatura área','endpoint','/areas',2,'abreviacion_area');
insert into campostablas (id_menu, tabla, nombre_campo, titulo_campo, tipo, backend, ancho, valores) values (15,'funcionario','name','Nombre y apellido','character','',255,'');
insert into campostablas (id_menu, tabla, nombre_campo, titulo_campo, tipo, backend, ancho, valores) values (15,'funcionario','position','Cargo','character','',255,'');
insert into campostablas (id_menu, tabla, nombre_campo, titulo_campo, tipo, backend, ancho, valores) values (15,'funcionario','image','Imagen','character','',255,'');
insert into campostablas (id_menu, tabla, nombre_campo, titulo_campo, tipo, backend, ancho, valores) values (15,'funcionario','link','Link de más información','character','',255,'');
insert into campostablas (id_menu, tabla, nombre_campo, titulo_campo, tipo, backend, ancho, valores) values (16,'memoria','periodo_memoria','Año memoria','number','',10,'');
insert into campostablas (id_menu, tabla, nombre_campo, titulo_campo, tipo, backend, ancho, valores) values (16,'memoria','descripcion_memoria','Descripción de memoria','character','',255,'');
insert into campostablas (id_menu, tabla, nombre_campo, titulo_campo, tipo, backend, ancho, valores) values (16,'memoria','url_memoria','Link de memoria','character','',255,'');
insert into campostablas (id_menu, tabla, nombre_campo, titulo_campo, tipo, backend, ancho, valores) values (17,'norma','tipo_norma','Tipo de norma','character','',255,'[Planes y Política,Instrumentos de Gestión]');
insert into campostablas (id_menu, tabla, nombre_campo, titulo_campo, tipo, backend, ancho, valores) values (17,'norma','denominacion_norma','Denominación de norma','character','',255,'');
insert into campostablas (id_menu, tabla, nombre_campo, titulo_campo, tipo, backend, ancho, valores) values (17,'norma','url_norma','Link de norma','character','',255,'');
insert into campostablas (id_menu, tabla, nombre_campo, titulo_campo, tipo, backend, ancho, valores) values (18,'noticia','titulo_noticia','Tìtulo de noticia','character','',255,'');
insert into campostablas (id_menu, tabla, nombre_campo, titulo_campo, tipo, backend, ancho, valores) values (18,'noticia','descripcion_noticia','Descripción de noticia','character','',2000,'');
insert into campostablas (id_menu, tabla, nombre_campo, titulo_campo, tipo, backend, ancho, valores) values (18,'noticia','fecha_noticia','Fecha de noticia','character','',50,'');
insert into campostablas (id_menu, tabla, nombre_campo, titulo_campo, tipo, backend, ancho, valores) values (18,'noticia','url_imagen_portada','Link de imagen de portada','character','',255,'');
insert into campostablas (id_menu, tabla, nombre_campo, titulo_campo, tipo, backend, ancho, valores) values (19,'proyecto','image','Imagen proyecto','character','',255,'');
insert into campostablas (id_menu, tabla, nombre_campo, titulo_campo, tipo, backend, ancho, valores) values (19,'proyecto','video','Video del proyecto','character','',255,'');
insert into campostablas (id_menu, tabla, nombre_campo, titulo_campo, tipo, backend, ancho, valores) values (19,'proyecto','title','Tìtulo del proyecto','character','',255,'');
insert into campostablas (id_menu, tabla, nombre_campo, titulo_campo, tipo, backend, ancho, valores) values (19,'proyecto','content','Descripción','character','',255,'');
insert into campostablas (id_menu, tabla, nombre_campo, titulo_campo, tipo, backend, ancho, valores) values (19,'proyecto','link','Link del proyecto','character','',255,'');
insert into campostablas (id_menu, tabla, nombre_campo, titulo_campo, tipo, backend, ancho, valores) values (20,'rendicion','descripcion_rendicion','Descripción rendición','character','',255,'');
insert into campostablas (id_menu, tabla, nombre_campo, titulo_campo, tipo, backend, ancho, valores) values (20,'rendicion','periodo_rendicion','Año rendición','number','',10,'');
insert into campostablas (id_menu, tabla, nombre_campo, titulo_campo, tipo, backend, ancho, valores) values (20,'rendicion','url_rendicion','Link de rendición','character','',255,'');
insert into campostablas (id_menu, tabla, nombre_campo, titulo_campo, tipo, backend, ancho, valores) values (20,'resolucion','periodo_resolucion','Periodo de resolución','number','',10,'');
insert into campostablas (id_menu, tabla, nombre_campo, titulo_campo, tipo, backend, ancho, valores) values (21,'resolucion','adicional_resolucion','Adicional resolución','char','',1,'');
insert into campostablas (id_menu, tabla, nombre_campo, titulo_campo, tipo, backend, ancho, valores) values (21,'resolucion','numero_resolucion','Número resolución','character','',255,'');
insert into campostablas (id_menu, tabla, nombre_campo, titulo_campo, tipo, backend, ancho, valores) values (21,'resolucion','sumilla_resolucion','Sumilla resolución','character','',255,'');
insert into campostablas (id_menu, tabla, nombre_campo, titulo_campo, tipo, backend, ancho, valores) values (21,'resolucion','url_documento_resolucion','Link del documento resolución','character','',255,'');
insert into campostablas (id_menu, tabla, nombre_campo, titulo_campo, tipo, backend, ancho, valores) values (21,'resolucion','abreviacion_area','Abreviatura área','endpoint','/areas',2,'abreviacion_area');
insert into campostablas (id_menu, tabla, nombre_campo, titulo_campo, tipo, backend, ancho, valores) values (22,'servicio','tipo_servicio','Tipo de servicio','array','',10,'[TUPA,TUSNE]');
insert into campostablas (id_menu, tabla, nombre_campo, titulo_campo, tipo, backend, ancho, valores) values (22,'servicio','flag_construccion','Construido','array','',2,'[SI,NO]');
insert into campostablas (id_menu, tabla, nombre_campo, titulo_campo, tipo, backend, ancho, valores) values (22,'servicio','flag_calculo','flag_calculo','array','',1,'[0,1]');
insert into campostablas (id_menu, tabla, nombre_campo, titulo_campo, tipo, backend, ancho, valores) values (22,'servicio','requisitos_servicio','Requisitos del servicio','string','',255,'');
insert into campostablas (id_menu, tabla, nombre_campo, titulo_campo, tipo, backend, ancho, valores) values (22,'servicio','flag_metraje','Servicio se calcula?','array','',2,'[SI,NO]');
insert into campostablas (id_menu, tabla, nombre_campo, titulo_campo, tipo, backend, ancho, valores) values (22,'servicio','metraje_inicial','Metraje inicial','decimal','',10,'');
insert into campostablas (id_menu, tabla, nombre_campo, titulo_campo, tipo, backend, ancho, valores) values (22,'servicio','metraje_final','Metraje final','decimal','',10,'');
insert into campostablas (id_menu, tabla, nombre_campo, titulo_campo, tipo, backend, ancho, valores) values (22,'servicio','periodo_servicio','Periodo de servicio','number','',10,'');
insert into campostablas (id_menu, tabla, nombre_campo, titulo_campo, tipo, backend, ancho, valores) values (22,'servicio','numero_servicio','Número de servicio','number','',10,'');
insert into campostablas (id_menu, tabla, nombre_campo, titulo_campo, tipo, backend, ancho, valores) values (22,'servicio','sub_nivel_servicio','Sub nivel servicio','number','',10,'');
insert into campostablas (id_menu, tabla, nombre_campo, titulo_campo, tipo, backend, ancho, valores) values (22,'servicio','flag_seleccion','Servicio seleccionable?','array','',1,'[0,1]');
insert into campostablas (id_menu, tabla, nombre_campo, titulo_campo, tipo, backend, ancho, valores) values (22,'servicio','denominacion_servicio','Denominación de servicio','string','',255,'');
insert into campostablas (id_menu, tabla, nombre_campo, titulo_campo, tipo, backend, ancho, valores) values (22,'servicio','por_uit','Porcentaje de UIT','decimal','',10,'');
insert into campostablas (id_menu, tabla, nombre_campo, titulo_campo, tipo, backend, ancho, valores) values (22,'servicio','monto_soles','Monto en soles','decimal','',10,'');
insert into campostablas (id_menu, tabla, nombre_campo, titulo_campo, tipo, backend, ancho, valores) values (22,'servicio','monto_uit','Monto de UIT','decimal','',10,'');
insert into campostablas (id_menu, tabla, nombre_campo, titulo_campo, tipo, backend, ancho, valores) values (7,'tipodocumento','descripcion_tipo_documento','Descripción tipo de documento','string','',255,'');
insert into campostablas (id_menu, tabla, nombre_campo, titulo_campo, tipo, backend, ancho, valores) values (7,'tipodocumento','codigo_tramite_documentario','Código trámite documentario','char','',20,'');
insert into campostablas (id_menu, tabla, nombre_campo, titulo_campo, tipo, backend, ancho, valores) values (9,'usuario','name','Nombre completo del usuario','string','',255,'');
insert into campostablas (id_menu, tabla, nombre_campo, titulo_campo, tipo, backend, ancho, valores) values (9,'usuario','email','Correo electrónico','string','',255,'');
insert into campostablas (id_menu, tabla, nombre_campo, titulo_campo, tipo, backend, ancho, valores) values (9,'usuario','profile','Perfil de usuario','array','',20,'[Administrador,Creador,Autorizador]');
insert into campostablas (id_menu, tabla, nombre_campo, titulo_campo, tipo, backend, ancho, valores) values (9,'usuario','password','Clave','password','',10,'');
insert into campostablas (id_menu, tabla, nombre_campo, titulo_campo, tipo, backend, ancho, valores) values (23,'video','titulo_video','Título de video','character','',255,'');
insert into campostablas (id_menu, tabla, nombre_campo, titulo_campo, tipo, backend, ancho, valores) values (23,'video','descripcion_video','Descripción de video','character','',2000,'');
insert into campostablas (id_menu, tabla, nombre_campo, titulo_campo, tipo, backend, ancho, valores) values (23,'video','fecha_video','Fecha de video','character','',50,'');
insert into campostablas (id_menu, tabla, nombre_campo, titulo_campo, tipo, backend, ancho, valores) values (23,'video','url_imagen_video','Link imagen del video','character','',255,'');
insert into campostablas (id_menu, tabla, nombre_campo, titulo_campo, tipo, backend, ancho, valores) values (23,'video','url_video','Link del video','character','',255,'');
