INSERT INTO departamentos (id, departamento) values (1,'Amazonas');
INSERT INTO departamentos (id, departamento) values (2,'Áncash');
INSERT INTO departamentos (id, departamento) values (3,'Apurímac');
INSERT INTO departamentos (id, departamento) values (4,'Arequipa');
INSERT INTO departamentos (id, departamento) values (5,'Ayacucho');
INSERT INTO departamentos (id, departamento) values (6,'Cajamarca');
INSERT INTO departamentos (id, departamento) values (7,'Callao');
INSERT INTO departamentos (id, departamento) values (8,'Cusco');
INSERT INTO departamentos (id, departamento) values (9,'Huancavelica');
INSERT INTO departamentos (id, departamento) values (10,'Huánuco');
INSERT INTO departamentos (id, departamento) values (11,'Ica');
INSERT INTO departamentos (id, departamento) values (12,'Junín');
INSERT INTO departamentos (id, departamento) values (13,'La Libertad');
INSERT INTO departamentos (id, departamento) values (14,'Lambayeque');
INSERT INTO departamentos (id, departamento) values (15,'Lima');
INSERT INTO departamentos (id, departamento) values (16,'Loreto');
INSERT INTO departamentos (id, departamento) values (17,'Madre de Dios');
INSERT INTO departamentos (id, departamento) values (18,'Moquegua');
INSERT INTO departamentos (id, departamento) values (19,'Pasco');
INSERT INTO departamentos (id, departamento) values (20,'Piura');
INSERT INTO departamentos (id, departamento) values (21,'Puno');
INSERT INTO departamentos (id, departamento) values (22,'San Martín');
INSERT INTO departamentos (id, departamento) values (23,'Tacna');
INSERT INTO departamentos (id, departamento) values (24,'Tumbes');
INSERT INTO departamentos (id, departamento) values (25,'Ucayali');
