INSERT INTO MENUS (primer_nivel, segundo_nivel, nombre_menu, etiqueta_menu, descripcion_menu, url) values ('1','0','Opciones Generales','Generales','Opciones Generales de la web','/Generales');
INSERT INTO MENUS (primer_nivel, segundo_nivel, nombre_menu, etiqueta_menu, descripcion_menu, url) values ('1','1','Areas','Areas','Administrador de Areas','/Areas');
INSERT INTO MENUS (primer_nivel, segundo_nivel, nombre_menu, etiqueta_menu, descripcion_menu, url) values ('1','2','Categorías','Categorías','Administrador de Categorías','/Categorías');
INSERT INTO MENUS (primer_nivel, segundo_nivel, nombre_menu, etiqueta_menu, descripcion_menu, url) values ('1','6','UIT','UIT','Administrador de UIT','/UIT');
INSERT INTO MENUS (primer_nivel, segundo_nivel, nombre_menu, etiqueta_menu, descripcion_menu, url) values ('1','7','Tipo de documento','Tipodoc','Administrador de Tipo de documento','/Tipodoc');
INSERT INTO MENUS (primer_nivel, segundo_nivel, nombre_menu, etiqueta_menu, descripcion_menu, url) values ('1','8','Usuarios','Usuarios','Administrador de Usuarios','/Usuarios');
INSERT INTO MENUS (primer_nivel, segundo_nivel, nombre_menu, etiqueta_menu, descripcion_menu, url) values ('2','0','Tablas para la Web','Web','Administrador de Tablas para la Web','/Web');
INSERT INTO MENUS (primer_nivel, segundo_nivel, nombre_menu, etiqueta_menu, descripcion_menu, url) values ('2','1','Convenios','Convenios','Administrador de Convenios','/Convenios');
INSERT INTO MENUS (primer_nivel, segundo_nivel, nombre_menu, etiqueta_menu, descripcion_menu, url) values ('2','2','Convocatorias','Convocatorias','Administrador de Convocatorias','/Convocatorias');
INSERT INTO MENUS (primer_nivel, segundo_nivel, nombre_menu, etiqueta_menu, descripcion_menu, url) values ('2','3','Cursos','Cursos','Administrador de Cursos','/Cursos');
INSERT INTO MENUS (primer_nivel, segundo_nivel, nombre_menu, etiqueta_menu, descripcion_menu, url) values ('2','4','Directivas','Directivas','Administrador de Directivas','/Directivas');
INSERT INTO MENUS (primer_nivel, segundo_nivel, nombre_menu, etiqueta_menu, descripcion_menu, url) values ('2','5','Funcionarios','Funcionarios','Administrador de Funcionarios','/Funcionarios');
INSERT INTO MENUS (primer_nivel, segundo_nivel, nombre_menu, etiqueta_menu, descripcion_menu, url) values ('2','6','Memorias','Memorias','Administrador de Memorias','/Memorias');
INSERT INTO MENUS (primer_nivel, segundo_nivel, nombre_menu, etiqueta_menu, descripcion_menu, url) values ('2','7','Normas','Normas','Administrador de Normas','/Normas');
INSERT INTO MENUS (primer_nivel, segundo_nivel, nombre_menu, etiqueta_menu, descripcion_menu, url) values ('2','8','Noticias','Noticias','Administrador de Noticias','/Noticias');
INSERT INTO MENUS (primer_nivel, segundo_nivel, nombre_menu, etiqueta_menu, descripcion_menu, url) values ('2','9','Proyectos','Proyectos','Administrador de Proyectos','/Proyectos');
INSERT INTO MENUS (primer_nivel, segundo_nivel, nombre_menu, etiqueta_menu, descripcion_menu, url) values ('2','10','Rendiciones','Rendiciones','Administrador de Rendiciones','/Rendiciones');
INSERT INTO MENUS (primer_nivel, segundo_nivel, nombre_menu, etiqueta_menu, descripcion_menu, url) values ('2','11','Resoluciones','Resoluciones','Administrador de Resoluciones','/Resoluciones');
INSERT INTO MENUS (primer_nivel, segundo_nivel, nombre_menu, etiqueta_menu, descripcion_menu, url) values ('2','12','Servicios','Servicios','Administrador de Servicios','/Servicios');
INSERT INTO MENUS (primer_nivel, segundo_nivel, nombre_menu, etiqueta_menu, descripcion_menu, url) values ('2','13','Videos','Videos','Administrador de Videos','/Videos');
