INSERT INTO noticias (id,titulo_noticia, descripcion_noticia, fecha_noticia, id_categoria_noticia, url_imagen_portada, autorizado, autorizado_por, activo)
VALUES (1,'Uniendo esfuerzos por un mejor catastro nacional con la Municipalidad Distrital de Atalaya', 'El Instituto Catastral de Lima (ICL) se reunió con el alcalde de la Municipalidad Provincial de Atalaya Francisco De Asis Mendoza De Souza para definir el Convenio Específico del Catastro urbano. Además estuvo presente el alcalde distrital de Tahuania de la Provincia de Atalaya Luis Fernando Arechaga García, quien mostró interés en el catastro y el desarrollo de su localidad.', 'Año 2023', 1, 'https://icl.gob.pe/wp-content/uploads/2023/08/DSC_0002-1024x683.jpg', 1, 'Migración', 1);

INSERT INTO noticias (id,titulo_noticia, descripcion_noticia, fecha_noticia, id_categoria_noticia, url_imagen_portada, autorizado, autorizado_por, activo)
VALUES (2,'SESIÓN ORDINARIA DE CONSEJO DIRECTIVO Nº 018', 'Celebramos la Sesión Ordinaria de Consejo Directivo Nº 018, conducida por el Dr. Luis Alfonso Molina Arles, presidente ejecutivo, junto a los miembros del Consejo Directivo Augusto Manuel Mendoza Castillo y David Fernando Albújar Mesta. Durante la sesión, se coordinó la firma del Convenio Marco con las municipalidades de Ancón, Punta Negra, Punta Hermosa y Bongará – Amazonas. ¡También damos la bienvenida a Andrés Augusto Palomino Márquez y Fernando Sandoval Ruiz como nuevos miembros del Consejo Directivo! ¡Seguimos avanzando juntos por un mejor catastro en Lima.', 'Año 2023', 1, 'https://icl.gob.pe/wp-content/uploads/2023/09/DSC_0058-ok-1024x683.jpg', 1, 'Migración', 1);

INSERT INTO noticias (id,titulo_noticia, descripcion_noticia, fecha_noticia, id_categoria_noticia, url_imagen_portada, autorizado, autorizado_por, activo)
VALUES (3,'REUNIÓN CON FUNCIONARIOS DE LA MUNICIPALIDAD DISTRITAL DE CHANCAY', '¡El Instituto Catastral de Lima continúa trabajando arduamente para llevar el catastro a cada distrito del país! En una reunión fructífera con funcionarios de la Municipalidad de Chancay, se coordinaron esfuerzos para poder desarrollar el catastro en su localidad. La presencia de los funcionarios del ICL, junto al Presidente del directorio, Luis Molina, demostraron el compromiso que tienen para llevar adelante esta importante labor. Esta colaboración en equipo es fundamental para garantizar un completo y preciso catastro nacional. Juntos, estamos construyendo un mejor futuro para los ciudadanos.', 'Año 2023', 1, 'https://icl.gob.pe/wp-content/uploads/2023/09/DSC_0992-1024x683.jpg', 1, 'Migración', 1);

INSERT INTO noticias (id,titulo_noticia, descripcion_noticia, fecha_noticia, id_categoria_noticia, url_imagen_portada, autorizado, autorizado_por, activo)
VALUES (4,'Convenio Marco con cinco Regiones del Perú', 'El Dr. Luis Molina Arles, Presidente Ejecutivo del Instituto Catastral de Lima, ha suscrito un trascendental Convenio Marco en compañía de distinguidos alcaldes provinciales representantes de 5 regiones del Perú. Eudomila Maximilla Cabanillas Ostos, Alcaldesa de la provincia de Ocros en la Región Ancash; Andrés Clodualdo Olivares Muñoz, Alcalde de la provincia de Canas en la Región Cusco; Nilser Tafur Peláez, Alcalde de la provincia de Rodríguez de Mendoza en la Región Amazonas; Rosell Nilver Mamani Hancco, Alcalde de la provincia de Melgar en la Región Puno; y Esteban Irene García, Alcalde de la provincia de Mariscal Cáceres en la Región San Martín. Este trascendental acuerdo tuvo como escenario el majestuoso Salón de los Espejos del Teatro Municipal de Lima, un espacio que simboliza la convergencia de esfuerzos entre instituciones con el fin de llevar adelante proyectos que impulsan el desarrollo del catastro. Este sistema es fundamental para el ordenamiento territorial y la gestación de planes y proyectos en beneficio de nuestros conciudadanos. Continuaremos avanzando mediante la firma de estos convenios estratégicos, siempre orientados al progreso de nuestra ciudad.', 'Año 2023', 1, 'https://icl.gob.pe/wp-content/uploads/2023/08/DSC_0280-OK-1024x683.jpg', 1, 'Migración', 1);

INSERT INTO noticias (id,titulo_noticia, descripcion_noticia, fecha_noticia, id_categoria_noticia, url_imagen_portada, autorizado, autorizado_por, activo)
VALUES (5,'Convenio de Cooperación Interinstitucional con la Municipalidad Distrital de Pucusana', '¡Promoviendo el desarrollo del catastro! El presidente ejecutivo del Instituto Catastral de Lima, Dr. Luis Molina Arles, firmó un importante Convenio Marco con el alcalde de Pucusana, Ing. Juan José Cuya Espinoza. Esta alianza estratégica tiene como objetivo unir esfuerzos entre ambas instituciones para ejecutar proyectos que impulsen el desarrollo del catastro en la jurisdicción local. El catastro es un instrumento esencial para el ordenamiento territorial y la formulación de planes y proyectos en beneficio del bienestar de nuestros vecinos. Estamos comprometidos en seguir fortaleciendo estas colaboraciones estratégicas para contribuir al crecimiento y desarrollo sostenible de nuestra ciudad. ¡Juntos construiremos un futuro mejor!', 'Año 2023', 1, 'https://icl.gob.pe/wp-content/uploads/2023/08/3I1A5974-1024x715.jpg', 1, 'Migración', 1);

INSERT INTO noticias (id,titulo_noticia, descripcion_noticia, fecha_noticia, id_categoria_noticia, url_imagen_portada, autorizado, autorizado_por, activo)
VALUES (6,'Convenio Marco de Cooperación Interinstitucional con la Municipalidad Provincial de Quispicanchi, departamento del Cuzco', '¡Importante alianza para el crecimiento del catastro! En un histórico encuentro, el Dr. Luis Molina Arles, Presidente Ejecutivo del Instituto Catastral de Lima (ICL), y el alcalde de la Municipalidad Provincial de Quispicanchi, Sr. Cirilo Vargas Huillca, firmaron un Convenio Marco de Cooperación Interinstitucional. Este acuerdo tiene como finalidad unir esfuerzos y recursos para impulsar el desarrollo del catastro en la provincia de Quispicanchi, ubicada en el departamento del Cuzco. El catastro es una herramienta fundamental para el ordenamiento territorial y el desarrollo de proyectos en beneficio de la comunidad. El ICL está comprometido en seguir colaborando con diversas instituciones para promover un mejor futuro para todos.', 'Año 2023', 1, 'https://icl.gob.pe/wp-content/uploads/2023/08/DSC_0263-OK-1024x683.jpg', 1, 'Migración', 1);

INSERT INTO noticias (id,titulo_noticia, descripcion_noticia, fecha_noticia, id_categoria_noticia, url_imagen_portada, autorizado, autorizado_por, activo) 
VALUES (7,'El Instituto Catastral de Lima se une al Simulacro Nacional Multipeligro', 'Para concientizar sobre la importancia de la preparación ante desastres. Como parte de los preparativos al simulacro, se participó de un pasacalle organizado por el Instituto Nacional de Defensa Civil Perú. Únete y demostremos nuestra capacidad de respuesta ante sismos. ¡No te pierdas el simulacro nacional el martes 15 a partir de las 3:00 pm', 'Año 2023', 1, 'https://icl.gob.pe/wp-content/uploads/2023/08/WMFU4015-scaled-e1692718674179-1024x688.jpg', 1, 'Migración', 1);

INSERT INTO noticias (id,titulo_noticia, descripcion_noticia, fecha_noticia, id_categoria_noticia, url_imagen_portada, autorizado, autorizado_por, activo) 
VALUES (8,'El presidente ejecutivo del ICL Dr. Luis Molina Arles recibió la visita del alcalde Alfonso Romero de la Municipalidad Provincial de San Pablo – Cajamarca', '¡Noticias emocionantes! El presidente ejecutivo del Instituto Catastral de Lima, Dr. Luis Molina Arles recibió la visita del alcalde Alfonso Romero Moza y el gerente municipal Hernando Villanueva Santa Cruz de la Municipalidad Provincial de San Pablo de la región de Cajamarca. En esta reunión, se abordaron temas importantes sobre fortalecimiento de relaciones institucionales hacia la firma de un convenio marco. Estamos entusiasmados por el potencial desarrollo y logros que esto traerá para la gestión territorial a través del catastro. ¡Sigamos trabajando juntos por un futuro próspero!', 'Año 2023', 1, 'https://icl.gob.pe/wp-content/uploads/2023/08/358610549_627866006107483_8304700009870880723_n-1024x683.jpg', 1, 'Migración', 1);

INSERT INTO noticias (id,titulo_noticia, descripcion_noticia, fecha_noticia, id_categoria_noticia, url_imagen_portada, autorizado, autorizado_por, activo) 
VALUES (9,'Primer Seminario: “Fortalecimiento de la Gestión del Catastro en Municipalidades Provinciales”', 'Municipalidades de diversas provincias del país, participaron del primer seminario “Fortalecimiento de la Gestión del Catastro en Municipalidades Provinciales” organizado por el Instituto Catastral de Lima. Luis Molina Arles, presidente ejecutivo del Instituto Catastral de Lima, recibió a los Alcaldes y delegaciones de San Román (Puno) Oscar Wyllams Caceres Rodriguez, Tocache (San Martín) Vidal Gonzales Zavaleta , Atalaya (Ucayali) Francisco De Asís Mendoza de Souza , San Pablo (Cajamarca) Alfonso Romero Moza, San Miguel (Cajamarca) José Carlos Quiroz, Paruro (Cuzco) Ricardo Cavero Cárdenas y Ucayali (Loreto) Rodolfo Lovo Tello. Este primer seminario, se expuso lo siguientes temas: Los efectos multi-propósitos del Catastro. El uso de la Cartografía para la gestión del Catastro Municipal. Contribución de la Información Catastral en la planificación del territorio. Y, la Gestión y financiamiento del Catastro en el marco del Sistema Nacional de Inversiones INVIERTE.PE Además, los participantes disfrutaron de un recorrido informativo por la Huaca Pucllana junto a la Directora del Museo de Sitio Pucllana, Micaela Alvarez Calmet. ¡Una experiencia enriquecedora para todos!”','Año 2023', 1, 'https://icl.gob.pe/wp-content/uploads/2023/08/DSC_0628-1024x683.jpg', 1, 'Migración', 1);

INSERT INTO noticias (id,titulo_noticia, descripcion_noticia, fecha_noticia, id_categoria_noticia, url_imagen_portada, autorizado, autorizado_por, activo) 
VALUES (10,'Convenio Marco de Cooperación Interinstitucional con la Municipalidad Distrital de Lurigancho – Chosica', 'El presidente ejecutivo del Instituto Catastral de Lima, Dr. Luis Molina Arles, concertó un importante Convenio Marco con el alcalde de la Municipalidad Distrital Lurigancho – Chosica, Oswaldo Vargas Cuellar a fin de unificar esfuerzos entre ambas instituciones para ejecutar proyectos que promuevan el desarrollo del catastro en la jurisdicción local, instrumento esencial para el ordenamiento territorial y la formulación de los planes y proyectos a favor del bienestar de los vecinos. Continuamos trabajando incansablemente para impulsar el desarrollo de nuestra población.','Año 2023', 1, 'https://icl.gob.pe/wp-content/uploads/2023/08/DSC_0097-1024x683.jpg', 1, 'Migración', 1);

INSERT INTO noticias (id,titulo_noticia, descripcion_noticia, fecha_noticia, id_categoria_noticia, url_imagen_portada, autorizado, autorizado_por, activo) 
VALUES (11,'Convenio Marco de Cooperación Inter-Institucional con la Municipalidad Distrital de Pacarán, Cañete.', 'El Gerente General del Instituto Catastral de Lima, Arq Julio Fuentes Vera y el Alcalde de la Municipalidad Distrital de Pacarán Neptali Rivas Santos, suscribieron el convenio marco de cooperación técnica, buscando fortalecer la colaboración en temas catastrales para beneficio mutuo y el desarrollo de su comunidad.', 'Año 2023',1, 'https://icl.gob.pe/wp-content/uploads/2023/07/1-B-1024x756.jpg', 1, 'Migración', 1);

INSERT INTO noticias (id,titulo_noticia, descripcion_noticia, fecha_noticia, id_categoria_noticia, url_imagen_portada, autorizado, autorizado_por, activo) 
VALUES (12,'Convenio Marco de Cooperación Interinstitucional con la Municipalidad Distrital de Magdalena del Mar', '¡Fomentando el desarrollo del catastro! El presidente ejecutivo del Instituto Catastral de Lima, Dr. Luis Molina Arles, concertó un trascendental Convenio Marco con el alcalde de Magdalena del Mar Francis Allison Oyague a a fin de unificar esfuerzos entre ambas instituciones para ejecutar proyectos que promuevan el desarrollo del catastro en la jurisdicción local, instrumento esencial para el ordenamiento territorial y la formulación de los planes y proyectos a favor del bienestar de los vecinos. Continuaremos con estos convenios estratégicos para el desarrollo de la ciudad.', 'Año 2023',1, 'https://icl.gob.pe/wp-content/uploads/2023/08/DSC_0022-1024x683.jpg', 1, 'Migración', 1);

INSERT INTO noticias (id,titulo_noticia, descripcion_noticia, fecha_noticia, id_categoria_noticia, url_imagen_portada, autorizado, autorizado_por, activo) 
VALUES (13,'Convenio Marco de Cooperación Interinstitucional con la Municipalidad Distrital de Independencia', '¡Fortaleciendo juntos en el catastro! El presidente ejecutivo del Instituto Catastral de Lima, Dr. Luis Molina Arles, concertó un trascendental Convenio Marco con el alcalde de Independencia. Alfredo Reynaga a fin de unificar esfuerzos entre ambas instituciones para ejecutar proyectos que promuevan el desarrollo del catastro en la jurisdicción local, instrumento esencial para el ordenamiento territorial y la formulación de los planes y proyectos a favor del bienestar de los vecinos. Continuaremos con estos convenios estratégicos para el desarrollo de la ciudad.', 'Año 2023',1, 'https://icl.gob.pe/wp-content/uploads/2023/08/DSC_0080-1024x698.jpg', 1, 'Migración', 1);

INSERT INTO noticias (id,titulo_noticia, descripcion_noticia, fecha_noticia, id_categoria_noticia, url_imagen_portada, autorizado, autorizado_por, activo) 
VALUES (14,'Convenio Marco de Cooperación Interinstitucional con la Municipalidad De San Bartolo', '¡IMPULSANDO EL DESARROLLO DEL CATASTRO! El presidente ejecutivo del Instituto Catastral de Lima, Dr. Luis Molina Arles, firmó un importante Convenio Marco con el alcalde de San Bartolo August Carbajal, a fin de unificar esfuerzos entre ambas instituciones para ejecutar proyectos que promuevan el desarrollo del catastro en la jurisdicción local, instrumento esencial para el ordenamiento territorial y la formulación de los planes y proyectos a favor del bienestar de los vecinos. Continuaremos con estos convenios estratégicos para el desarrollo de la ciudad.','Año 2023', 1, 'https://icl.gob.pe/wp-content/uploads/2023/08/1-1024x683.jpg', 1, 'Migración', 1);

INSERT INTO noticias (id,titulo_noticia, descripcion_noticia, fecha_noticia, id_categoria_noticia, url_imagen_portada, autorizado, autorizado_por, activo)
VALUES (15,'Convenio Marco de Cooperación Interinstitucional con la Municipalidad De San Miguel', '¡PROMOVIENDO EL DESARROLLO DEL CATASTRO! El presidente ejecutivo del Instituto Catastral de Lima, Dr. Luis Molina Arles, firmó un importante Convenio Marco con el alcalde de San Miguel Eduardo Bless, a fin de aunar esfuerzos entre ambas instituciones para ejecutar proyectos que promuevan el desarrollo del catastro en la jurisdicción local, instrumento esencial para el ordenamiento territorial y la formulación de los planes y proyectos a favor del bienestar de los vecinos. Continuaremos con estos convenios estratégicos para el desarrollo de la ciudad.', 'Año 2023', 1, 'https://icl.gob.pe/wp-content/uploads/2023/08/DSC_0023-1024x683.jpg', 1, 'Migración', 1);

INSERT INTO noticias (id,titulo_noticia, descripcion_noticia, fecha_noticia, id_categoria_noticia, url_imagen_portada, autorizado, autorizado_por, activo)
VALUES (16,'Convenio Marco de Cooperación Interinstitucional con la Municipalidad Distrital de Santa Anita', '¡PROMOVIENDO EL DESARROLLO DEL CATASTRO! El presidente ejecutivo del Instituto Catastral de Lima, Dr. Luis Molina Arles, firmó un importante Convenio Marco con el alcalde de Santa Anita, Olimpio Alegría Calderón, a fin de aunar esfuerzos entre ambas instituciones para ejecutar proyectos que promuevan el desarrollo del catastro en la jurisdicción local, instrumento esencial para el ordenamiento territorial y la formulación de los planes y proyectos de desarrollo a favor del bienestar de los vecinos.', 'Año 2023', 1, 'https://icl.gob.pe/wp-content/uploads/2023/08/DSC_0105-1024x683.jpg', 1, 'Migración', 1);

INSERT INTO noticias (id,titulo_noticia, descripcion_noticia, fecha_noticia, id_categoria_noticia, url_imagen_portada, autorizado, autorizado_por, activo)
VALUES (17,'Visita del Archivo General de la Nación representado por la Sra. Carmen Aliaga y la Sra. Marlitt Rodríguez', 'Tuvimos una importante visita del Archivo General de la Nación representado por la Sra. Carmen Aliaga y la Sra. Marlitt Rodríguez, para garantizar el cumplimiento de las normas y procedimientos archivísticos. Además, se llevó a cabo una charla de Orientación de la Norma Archivística. En el ICL, estamos comprometidos con la calidad de nuestros servicios, y esta visita de supervisión nos permite garantizar la transparencia, accesibilidad y protección de la información contenida en nuestros archivos.', 'Año 2023', 1, 'https://icl.gob.pe/wp-content/uploads/2023/08/1-1-1024x683.jpg', 1, 'Migración', 1);

INSERT INTO noticias (id,titulo_noticia, descripcion_noticia, fecha_noticia, id_categoria_noticia, url_imagen_portada, autorizado, autorizado_por, activo)
VALUES (18,'Reunión de coordinación con el alcalde Alfredo Reynaga de la Municipalidad Independencia', 'El Presidente Ejecutivo del ICL, Luis Molina Arles sostuvo una importante reunión de coordinación con el alcalde Alfredo Reynaga de la Municipalidad de Independencia, para la suscripción del Convenio Marco de Cooperación Técnica Interinstitucional. El Instituto Catastral de Lima está comprometido en seguir trabajando para impulsar el desarrollo y modernización del catastro.', 'Año 2023', 1, 'https://icl.gob.pe/wp-content/uploads/2023/08/1-2-1024x683.jpg', 1, 'Migración', 1);

INSERT INTO noticias (id,titulo_noticia, descripcion_noticia, fecha_noticia, id_categoria_noticia, url_imagen_portada, autorizado, autorizado_por, activo)
VALUES (19,'Convenio de Cooperación Interinstitucional con la Municipalidad Distrital de Santa Rosa', '¡Grandes noticias para el distrito de Santa Rosa! Hoy, el Presidente Ejecutivo del Instituto Catastral de Lima, Luis Molina Arles y el alcalde de la Municipalidad Distrital de Santa Rosa, George Robles, firmaron un Convenio Marco de Cooperación Técnico Interinstitucional. En la ceremonia, el Dr. Molina expresó el saludo del alcalde de la Municipalidad de Lima, Rafael López Aliaga ¿Qué significa esto? ¡La formulación y ejecución de proyectos que promuevan el desarrollo del catastro. ¡Sigamos trabajando en beneficio del desarrollo del distrito de Santa Rosa y el progreso de sus vecinos!', 'Año 2023', 1, 'https://icl.gob.pe/wp-content/uploads/2023/08/341529321_1606521256493806_6982873249408148708_n-1.jpg', 1, 'Migración', 1);

INSERT INTO noticias (id,titulo_noticia, descripcion_noticia, fecha_noticia, id_categoria_noticia, url_imagen_portada, autorizado, autorizado_por, activo)
VALUES (20,'Convenio Marco de Cooperación Interinstitucional con la Municipalidad de Barranco', 'El presidente ejecutivo del Instituto Catastral de Lima, Dr. Luis Molina Arles, y la alcaldesa de Barranco, Jessica Vargas, suscribieron el Convenio Marco de Cooperación Inter-Institucional entre el ICL y la Municipalidad Distrital de Barranco. En la ceremonia, el Dr. Molina expresó el saludo del alcalde de Lima, Ing. Rafael López Aliaga, y resaltó la alianza entre ambas instituciones para aunar esfuerzos con el objetivo principal de que Barranco cuente con un catastro moderno y sobre todo actualizado, que es una herramienta esencial para el desarrollo del distrito y lograr el bienestar de los vecinos.', 'Año 2023', 1, 'https://icl.gob.pe/wp-content/uploads/2023/04/MDB_5676-1024x683.jpg', 1, 'Migración', 1);

INSERT INTO noticias (id,titulo_noticia, descripcion_noticia, fecha_noticia, id_categoria_noticia, url_imagen_portada, autorizado, autorizado_por, activo)
VALUES (21,'Reunión de coordinación con el Servicio de Administración de Lima', 'El gerente de Cartografía y Tecnología de la Información del Instituto Catastal de Lima, Ing. Alonso Guardia junto a su equipo, sostuvieron una reunión productiva con la gerente de Fiscalización del SAT de Lima, Giovanna Retis, el gerente Central de Inovación y Proyectos, Waldir Tume y el gerente de Informática, Sandro Rodriguez, con el objetivo de trabajar de manera articulada en la actualización de los datos a nivel catastral de los predios de Cercado de Lima.', 'Año 2023', 1, 'https://icl.gob.pe/wp-content/uploads/2023/08/1A-1024x683.jpg', 1, 'Migración', 1);

INSERT INTO noticias (id,titulo_noticia, descripcion_noticia, fecha_noticia, id_categoria_noticia, url_imagen_portada, autorizado, autorizado_por, activo)
VALUES (22,'El Instituto Catastral de Lima y la Municipalidad de la Molina', 'El gerente general del Instituto Catastral de Lima, Arq. Julio Fuentes, junto a otros funcionarios, sostuvieron una importante reunión con los representantes de la Municipalidad de la Molina, el gerente de Desarrollo Urbano, Eusebio Cabrera y el subgerente de Planeamiento, Inversiones y Modernización del Estado, Tatiana Naldos; donde ambas instituciones se mostraron interesados en trabajar de forma conjunta en el desarrollo de nuevas aplicaciones tecnológicas para acceder a la información cartográfica.', 'Año 2023', 1, 'https://icl.gob.pe/wp-content/uploads/2023/08/1C-1024x683.jpg', 1, 'Migración', 1);

INSERT INTO noticias (id,titulo_noticia, descripcion_noticia, fecha_noticia, id_categoria_noticia, url_imagen_portada, autorizado, autorizado_por, activo)
VALUES (23,'Convenio de Cooperación Interinstitucional con la Municipalidad Provincial de Ica', 'El alcalde de la Municipalidad Metropolitana de Lima; Dr. Rafael López Aliaga, extendió sus saludos a la ciudad del eterno sol a través del presidente ejecutivo del Instituto Catastral de Lima; Dr. Luis Alfonso Molina Arles, quien firmó junto al alcalde Provincial de Ica; Ing. Carlos Reyes Roque el Convenio Marco de Cooperación Inter-Institucional entre ambas instituciones. Gracias a esta alianza estratégica nos permitirá trabajar de manera articulada para la implementación de nuevas herramientas tecnológicas actualizadas a nivel catastral que mejorará el ordenamiento territorial y desarrollará estrategias para una mejor calidad de vida del pueblo iqueño.', 'Año 2023', 1, 'https://icl.gob.pe/wp-content/uploads/2023/08/1D-1024x683.jpg', 1, 'Migración', 1);

INSERT INTO noticias (id,titulo_noticia, descripcion_noticia, fecha_noticia, id_categoria_noticia, url_imagen_portada, autorizado, autorizado_por, activo)
VALUES (24,'Formando alianzas para futuros proyectos catastrales en Lima Metropolitana', 'En el Instituto Catastral de Lima trabajamos para mantener actualizado el catastro de la metrópoli, en ese sentido; participamos de la reunión con el representante del Banco Mundial y funcionarios de la Municipalidad Metropolitana de Lima, para coordinar y articular esfuerzos en los proyectos catastrales a ejecutar en la ciudad de Lima, que beneficiarán a la ciudadanía.', 'Año 2023', 1, 'https://icl.gob.pe/wp-content/uploads/2023/08/DSC_4985-1024x683.jpg', 1, 'Migración', 1);

INSERT INTO noticias (id,titulo_noticia, descripcion_noticia, fecha_noticia, id_categoria_noticia, url_imagen_portada, autorizado, autorizado_por, activo)
VALUES (25,'Sesión de Consejo Ordinaria Directivo', 'En las instalaciones del Instituto Catastral de Lima se llevó a cabo la tercera Sesión Ordinaria de Concejo Directivo presidida por el Presidente Ejecutivo, Dr. Luis Alfonso Molina Arles y sus miembros del Consejo Directivo para la presentación de los informes situacionales que vienen realizando nuestros colaboradores en favor de la comunidad.', 'Año 2023', 1, 'https://icl.gob.pe/wp-content/uploads/2023/04/DSC_0088-3-1024x674.jpg', 1, 'Migración', 1);
