INSERT INTO provincias (id, provincia, id_departamento) values (1,'Chachapoyas',1);
INSERT INTO provincias (id, provincia, id_departamento) values (2,'Bagua',1);
INSERT INTO provincias (id, provincia, id_departamento) values (3,'Bongará',1);
INSERT INTO provincias (id, provincia, id_departamento) values (4,'Condorcanqui',1);
INSERT INTO provincias (id, provincia, id_departamento) values (5,'Luya',1);
INSERT INTO provincias (id, provincia, id_departamento) values (6,'Rodríguez de Mendoza',1);
INSERT INTO provincias (id, provincia, id_departamento) values (7,'Utcubamba',1);
INSERT INTO provincias (id, provincia, id_departamento) values (8,'Huaraz',2);
INSERT INTO provincias (id, provincia, id_departamento) values (9,'Aija',2);
INSERT INTO provincias (id, provincia, id_departamento) values (10,'Antonio Raimondi',2);
INSERT INTO provincias (id, provincia, id_departamento) values (11,'Asunción',2);
INSERT INTO provincias (id, provincia, id_departamento) values (12,'Bolognesi',2);
INSERT INTO provincias (id, provincia, id_departamento) values (13,'Carhuaz',2);
INSERT INTO provincias (id, provincia, id_departamento) values (14,'Carlos Fermín Fitzcarrald',2);
INSERT INTO provincias (id, provincia, id_departamento) values (15,'Casma',2);
INSERT INTO provincias (id, provincia, id_departamento) values (16,'Corongo',2);
INSERT INTO provincias (id, provincia, id_departamento) values (17,'Huari',2);
INSERT INTO provincias (id, provincia, id_departamento) values (18,'Huarmey',2);
INSERT INTO provincias (id, provincia, id_departamento) values (19,'Huaylas',2);
INSERT INTO provincias (id, provincia, id_departamento) values (20,'Mariscal Luzuriaga',2);
INSERT INTO provincias (id, provincia, id_departamento) values (21,'Ocros',2);
INSERT INTO provincias (id, provincia, id_departamento) values (22,'Pallasca',2);
INSERT INTO provincias (id, provincia, id_departamento) values (23,'Pomabamba',2);
INSERT INTO provincias (id, provincia, id_departamento) values (24,'Recuay',2);
INSERT INTO provincias (id, provincia, id_departamento) values (25,'Santa',2);
INSERT INTO provincias (id, provincia, id_departamento) values (26,'Sihuas',2);
INSERT INTO provincias (id, provincia, id_departamento) values (27,'Yungay',2);
INSERT INTO provincias (id, provincia, id_departamento) values (28,'Abancay',3);
INSERT INTO provincias (id, provincia, id_departamento) values (29,'Andahuaylas',3);
INSERT INTO provincias (id, provincia, id_departamento) values (30,'Antabamba',3);
INSERT INTO provincias (id, provincia, id_departamento) values (31,'Aymaraes',3);
INSERT INTO provincias (id, provincia, id_departamento) values (32,'Cotabambas',3);
INSERT INTO provincias (id, provincia, id_departamento) values (33,'Chincheros',3);
INSERT INTO provincias (id, provincia, id_departamento) values (34,'Grau',3);
INSERT INTO provincias (id, provincia, id_departamento) values (35,'Arequipa',4);
INSERT INTO provincias (id, provincia, id_departamento) values (36,'Camaná',4);
INSERT INTO provincias (id, provincia, id_departamento) values (37,'Caravelí',4);
INSERT INTO provincias (id, provincia, id_departamento) values (38,'Castilla',4);
INSERT INTO provincias (id, provincia, id_departamento) values (39,'Caylloma',4);
INSERT INTO provincias (id, provincia, id_departamento) values (40,'Condesuyos',4);
INSERT INTO provincias (id, provincia, id_departamento) values (41,'Islay',4);
INSERT INTO provincias (id, provincia, id_departamento) values (42,'La Unión',4);
INSERT INTO provincias (id, provincia, id_departamento) values (43,'Huamanga',5);
INSERT INTO provincias (id, provincia, id_departamento) values (44,'Cangallo',5);
INSERT INTO provincias (id, provincia, id_departamento) values (45,'Huanca Sancos',5);
INSERT INTO provincias (id, provincia, id_departamento) values (46,'Huanta',5);
INSERT INTO provincias (id, provincia, id_departamento) values (47,'La Mar',5);
INSERT INTO provincias (id, provincia, id_departamento) values (48,'Lucanas',5);
INSERT INTO provincias (id, provincia, id_departamento) values (49,'Parinacochas',5);
INSERT INTO provincias (id, provincia, id_departamento) values (50,'Páucar del Sara Sara',5);
INSERT INTO provincias (id, provincia, id_departamento) values (51,'Sucre',5);
INSERT INTO provincias (id, provincia, id_departamento) values (52,'Víctor Fajardo',5);
INSERT INTO provincias (id, provincia, id_departamento) values (53,'Vilcas Huamán',5);
INSERT INTO provincias (id, provincia, id_departamento) values (54,'Cajamarca',6);
INSERT INTO provincias (id, provincia, id_departamento) values (55,'Cajabamba',6);
INSERT INTO provincias (id, provincia, id_departamento) values (56,'Celendín',6);
INSERT INTO provincias (id, provincia, id_departamento) values (57,'Chota',6);
INSERT INTO provincias (id, provincia, id_departamento) values (58,'Contumazá',6);
INSERT INTO provincias (id, provincia, id_departamento) values (59,'Cutervo',6);
INSERT INTO provincias (id, provincia, id_departamento) values (60,'Hualgayoc',6);
INSERT INTO provincias (id, provincia, id_departamento) values (61,'Jaén',6);
INSERT INTO provincias (id, provincia, id_departamento) values (62,'San Ignacio',6);
INSERT INTO provincias (id, provincia, id_departamento) values (63,'San Marcos',6);
INSERT INTO provincias (id, provincia, id_departamento) values (64,'San Miguel',6);
INSERT INTO provincias (id, provincia, id_departamento) values (65,'San Pablo',6);
INSERT INTO provincias (id, provincia, id_departamento) values (66,'Santa Cruz',6);
INSERT INTO provincias (id, provincia, id_departamento) values (67,'Callao',7);
INSERT INTO provincias (id, provincia, id_departamento) values (68,'Cusco',8);
INSERT INTO provincias (id, provincia, id_departamento) values (69,'Acomayo',8);
INSERT INTO provincias (id, provincia, id_departamento) values (70,'Anta',8);
INSERT INTO provincias (id, provincia, id_departamento) values (71,'Calca',8);
INSERT INTO provincias (id, provincia, id_departamento) values (72,'Canas',8);
INSERT INTO provincias (id, provincia, id_departamento) values (73,'Canchis',8);
INSERT INTO provincias (id, provincia, id_departamento) values (74,'Chumbivilcas',8);
INSERT INTO provincias (id, provincia, id_departamento) values (75,'Espinar',8);
INSERT INTO provincias (id, provincia, id_departamento) values (76,'La Convención',8);
INSERT INTO provincias (id, provincia, id_departamento) values (77,'Paruro',8);
INSERT INTO provincias (id, provincia, id_departamento) values (78,'Paucartambo',8);
INSERT INTO provincias (id, provincia, id_departamento) values (79,'Quispicanchi',8);
INSERT INTO provincias (id, provincia, id_departamento) values (80,'Urubamba',8);
INSERT INTO provincias (id, provincia, id_departamento) values (81,'Huancavelica',9);
INSERT INTO provincias (id, provincia, id_departamento) values (82,'Acobamba',9);
INSERT INTO provincias (id, provincia, id_departamento) values (83,'Angaraes',9);
INSERT INTO provincias (id, provincia, id_departamento) values (84,'Castrovirreyna',9);
INSERT INTO provincias (id, provincia, id_departamento) values (85,'Churcampa',9);
INSERT INTO provincias (id, provincia, id_departamento) values (86,'Huaytará',9);
INSERT INTO provincias (id, provincia, id_departamento) values (87,'Tayacaja',9);
INSERT INTO provincias (id, provincia, id_departamento) values (88,'Huánuco',10);
INSERT INTO provincias (id, provincia, id_departamento) values (89,'Ambo',10);
INSERT INTO provincias (id, provincia, id_departamento) values (90,'Dos de Mayo',10);
INSERT INTO provincias (id, provincia, id_departamento) values (91,'Huacaybamba',10);
INSERT INTO provincias (id, provincia, id_departamento) values (92,'Huamalíes',10);
INSERT INTO provincias (id, provincia, id_departamento) values (93,'Leoncio Prado',10);
INSERT INTO provincias (id, provincia, id_departamento) values (94,'Marañón',10);
INSERT INTO provincias (id, provincia, id_departamento) values (95,'Pachitea',10);
INSERT INTO provincias (id, provincia, id_departamento) values (96,'Puerto Inca',10);
INSERT INTO provincias (id, provincia, id_departamento) values (97,'Lauricocha',10);
INSERT INTO provincias (id, provincia, id_departamento) values (98,'Yarowilca',10);
INSERT INTO provincias (id, provincia, id_departamento) values (99,'Ica',11);
INSERT INTO provincias (id, provincia, id_departamento) values (100,'Chincha',11);
INSERT INTO provincias (id, provincia, id_departamento) values (101,'Nazca',11);
INSERT INTO provincias (id, provincia, id_departamento) values (102,'Palpa',11);
INSERT INTO provincias (id, provincia, id_departamento) values (103,'Pisco',11);
INSERT INTO provincias (id, provincia, id_departamento) values (104,'Huancayo',12);
INSERT INTO provincias (id, provincia, id_departamento) values (105,'Concepción',12);
INSERT INTO provincias (id, provincia, id_departamento) values (106,'Chanchamayo',12);
INSERT INTO provincias (id, provincia, id_departamento) values (107,'Jauja',12);
INSERT INTO provincias (id, provincia, id_departamento) values (108,'Junín',12);
INSERT INTO provincias (id, provincia, id_departamento) values (109,'Satipo',12);
INSERT INTO provincias (id, provincia, id_departamento) values (110,'Tarma',12);
INSERT INTO provincias (id, provincia, id_departamento) values (111,'Yauli',12);
INSERT INTO provincias (id, provincia, id_departamento) values (112,'Chupaca',12);
INSERT INTO provincias (id, provincia, id_departamento) values (113,'Trujillo',13);
INSERT INTO provincias (id, provincia, id_departamento) values (114,'Ascope',13);
INSERT INTO provincias (id, provincia, id_departamento) values (115,'Bolívar',13);
INSERT INTO provincias (id, provincia, id_departamento) values (116,'Chepén',13);
INSERT INTO provincias (id, provincia, id_departamento) values (117,'Julcán',13);
INSERT INTO provincias (id, provincia, id_departamento) values (118,'Otuzco',13);
INSERT INTO provincias (id, provincia, id_departamento) values (119,'Pacasmayo',13);
INSERT INTO provincias (id, provincia, id_departamento) values (120,'Pataz',13);
INSERT INTO provincias (id, provincia, id_departamento) values (121,'Sánchez Carrión',13);
INSERT INTO provincias (id, provincia, id_departamento) values (122,'Santiago de Chuco',13);
INSERT INTO provincias (id, provincia, id_departamento) values (123,'Gran Chimú',13);
INSERT INTO provincias (id, provincia, id_departamento) values (124,'Virú',13);
INSERT INTO provincias (id, provincia, id_departamento) values (125,'Chiclayo',14);
INSERT INTO provincias (id, provincia, id_departamento) values (126,'Ferreñafe',14);
INSERT INTO provincias (id, provincia, id_departamento) values (127,'Lambayeque',14);
INSERT INTO provincias (id, provincia, id_departamento) values (128,'Lima',15);
INSERT INTO provincias (id, provincia, id_departamento) values (129,'Barranca',15);
INSERT INTO provincias (id, provincia, id_departamento) values (130,'Cajatambo',15);
INSERT INTO provincias (id, provincia, id_departamento) values (131,'Canta',15);
INSERT INTO provincias (id, provincia, id_departamento) values (132,'Cañete',15);
INSERT INTO provincias (id, provincia, id_departamento) values (133,'Huaral',15);
INSERT INTO provincias (id, provincia, id_departamento) values (134,'Huarochirí',15);
INSERT INTO provincias (id, provincia, id_departamento) values (135,'Huaura',15);
INSERT INTO provincias (id, provincia, id_departamento) values (136,'Oyón',15);
INSERT INTO provincias (id, provincia, id_departamento) values (137,'Yauyos',15);
INSERT INTO provincias (id, provincia, id_departamento) values (138,'Maynas',16);
INSERT INTO provincias (id, provincia, id_departamento) values (139,'Alto Amazonas',16);
INSERT INTO provincias (id, provincia, id_departamento) values (140,'Loreto',16);
INSERT INTO provincias (id, provincia, id_departamento) values (141,'Mariscal Ramón Castilla',16);
INSERT INTO provincias (id, provincia, id_departamento) values (142,'Requena',16);
INSERT INTO provincias (id, provincia, id_departamento) values (143,'Ucayali',16);
INSERT INTO provincias (id, provincia, id_departamento) values (144,'Datem del Marañón',16);
INSERT INTO provincias (id, provincia, id_departamento) values (145,'Putumayo',16);
INSERT INTO provincias (id, provincia, id_departamento) values (146,'Tambopata',17);
INSERT INTO provincias (id, provincia, id_departamento) values (147,'Manu',17);
INSERT INTO provincias (id, provincia, id_departamento) values (148,'Tahuamanu',17);
INSERT INTO provincias (id, provincia, id_departamento) values (149,'Mariscal Nieto',18);
INSERT INTO provincias (id, provincia, id_departamento) values (150,'General Sánchez Cerro',18);
INSERT INTO provincias (id, provincia, id_departamento) values (151,'Ilo',18);
INSERT INTO provincias (id, provincia, id_departamento) values (152,'Pasco',19);
INSERT INTO provincias (id, provincia, id_departamento) values (153,'Daniel Alcides Carrión',19);
INSERT INTO provincias (id, provincia, id_departamento) values (154,'Oxapampa',19);
INSERT INTO provincias (id, provincia, id_departamento) values (155,'Piura',20);
INSERT INTO provincias (id, provincia, id_departamento) values (156,'Ayabaca',20);
INSERT INTO provincias (id, provincia, id_departamento) values (157,'Huancabamba',20);
INSERT INTO provincias (id, provincia, id_departamento) values (158,'Morropón',20);
INSERT INTO provincias (id, provincia, id_departamento) values (159,'Paita',20);
INSERT INTO provincias (id, provincia, id_departamento) values (160,'Sullana',20);
INSERT INTO provincias (id, provincia, id_departamento) values (161,'Talara',20);
INSERT INTO provincias (id, provincia, id_departamento) values (162,'Sechura',20);
INSERT INTO provincias (id, provincia, id_departamento) values (163,'Puno',21);
INSERT INTO provincias (id, provincia, id_departamento) values (164,'Azángaro',21);
INSERT INTO provincias (id, provincia, id_departamento) values (165,'Carabaya',21);
INSERT INTO provincias (id, provincia, id_departamento) values (166,'Chucuito',21);
INSERT INTO provincias (id, provincia, id_departamento) values (167,'El Collao',21);
INSERT INTO provincias (id, provincia, id_departamento) values (168,'Huancané',21);
INSERT INTO provincias (id, provincia, id_departamento) values (169,'Lampa',21);
INSERT INTO provincias (id, provincia, id_departamento) values (170,'Melgar',21);
INSERT INTO provincias (id, provincia, id_departamento) values (171,'Moho',21);
INSERT INTO provincias (id, provincia, id_departamento) values (172,'San Antonio de Putina',21);
INSERT INTO provincias (id, provincia, id_departamento) values (173,'San Román',21);
INSERT INTO provincias (id, provincia, id_departamento) values (174,'Sandia',21);
INSERT INTO provincias (id, provincia, id_departamento) values (175,'Yunguyo',21);
INSERT INTO provincias (id, provincia, id_departamento) values (176,'Moyobamba',22);
INSERT INTO provincias (id, provincia, id_departamento) values (177,'Bellavista',22);
INSERT INTO provincias (id, provincia, id_departamento) values (178,'El Dorado',22);
INSERT INTO provincias (id, provincia, id_departamento) values (179,'Huallaga',22);
INSERT INTO provincias (id, provincia, id_departamento) values (180,'Lamas',22);
INSERT INTO provincias (id, provincia, id_departamento) values (181,'Mariscal Cáceres',22);
INSERT INTO provincias (id, provincia, id_departamento) values (182,'Picota',22);
INSERT INTO provincias (id, provincia, id_departamento) values (183,'Rioja',22);
INSERT INTO provincias (id, provincia, id_departamento) values (184,'San Martín',22);
INSERT INTO provincias (id, provincia, id_departamento) values (185,'Tocache',22);
INSERT INTO provincias (id, provincia, id_departamento) values (186,'Tacna',23);
INSERT INTO provincias (id, provincia, id_departamento) values (187,'Candarave',23);
INSERT INTO provincias (id, provincia, id_departamento) values (188,'Jorge Basadre',23);
INSERT INTO provincias (id, provincia, id_departamento) values (189,'Tarata',23);
INSERT INTO provincias (id, provincia, id_departamento) values (190,'Tumbes',24);
INSERT INTO provincias (id, provincia, id_departamento) values (191,'Contralmirante Villar',24);
INSERT INTO provincias (id, provincia, id_departamento) values (192,'Zarumilla',24);
INSERT INTO provincias (id, provincia, id_departamento) values (193,'Coronel Portillo',25);
INSERT INTO provincias (id, provincia, id_departamento) values (194,'Atalaya',25);
INSERT INTO provincias (id, provincia, id_departamento) values (195,'Padre Abad',25);
INSERT INTO provincias (id, provincia, id_departamento) values (196,'Purús',25);